# Generated by Django 4.0.5 on 2022-06-20 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tags',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
