# Generated by Django 4.0.5 on 2022-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_tags_post_alter_tags_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='post',
        ),
        migrations.AddField(
            model_name='tags',
            name='post',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
